// Curated preset builds — themed pet combos users can pick in one step
// instead of choosing each attribute individually.

export const PRESETS = [
  {
    name: 'Arcane Dragon',
    description: 'A legendary wizard dragon with starry eyes',
    species: 'dragon',
    rarity: 'legendary',
    eye: '✦',
    hat: 'wizard',
  },
  {
    name: 'Royal Capybara',
    description: 'An epic crowned capybara — chill royalty',
    species: 'capybara',
    rarity: 'epic',
    eye: '◉',
    hat: 'crown',
  },
  {
    name: 'Ghost in the Shell',
    description: 'A rare halo ghost with hollow eyes',
    species: 'ghost',
    rarity: 'rare',
    eye: '°',
    hat: 'halo',
  },
  {
    name: 'Dapper Penguin',
    description: 'An epic penguin in a top hat — class act',
    species: 'penguin',
    rarity: 'epic',
    eye: '·',
    hat: 'tophat',
  },
  {
    name: 'Mad Scientist',
    description: 'A legendary robot with glitchy eyes and propeller',
    species: 'robot',
    rarity: 'legendary',
    eye: '×',
    hat: 'propeller',
  },
  {
    name: 'Cozy Cat',
    description: 'A rare beanie cat with dreamy eyes',
    species: 'cat',
    rarity: 'rare',
    eye: '°',
    hat: 'beanie',
  },
  {
    name: 'Chaos Duck',
    description: 'An uncommon duck — simple but unhinged',
    species: 'duck',
    rarity: 'uncommon',
    eye: '×',
    hat: 'tinyduck',
  },
  {
    name: 'Mystic Owl',
    description: 'A legendary wizard owl with piercing gaze',
    species: 'owl',
    rarity: 'legendary',
    eye: '◉',
    hat: 'wizard',
  },
  {
    name: 'Spore Lord',
    description: 'An epic crowned mushroom — ruler of the forest floor',
    species: 'mushroom',
    rarity: 'epic',
    eye: '✦',
    hat: 'crown',
  },
  {
    name: 'Tiny Tank',
    description: 'A rare turtle with a propeller — slow but airborne',
    species: 'turtle',
    rarity: 'rare',
    eye: '·',
    hat: 'propeller',
  },
];
